name: Install Karpenter

on:
  workflow_dispatch:
    inputs:
      environment:
        type: choice
        required: true
        description: Environment you want to deploy in
        options:
          - poc
          - uat
          - prod
      action:
        type: choice
        required: true
        description: create or destroy
        options:
          - create/update
          - destroy
      eks_cluster_name:
        type: string
        required: true
        description: EKS cluster name
      karpenter_version:
        type: string
        required: false
        default: 1.3.3

permissions:
  id-token: write
  contents: write
  actions: read

run-name: "${{ github.event.inputs.environment }} Karpenter Setup (Mode: ${{ github.event.inputs.action }})"

jobs:
  Setup-Karpenter:
    name: ${{ github.event.inputs.action }} Karpenter Setup
    runs-on: self-hosted
    if: ${{ always() && !cancelled() }}
    timeout-minutes: 10
    defaults:
      run:
        working-directory: infra-setup
    steps:
      - name: Git clone the repository
        uses: actions/checkout@v4

      - name: Login into AWS
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ vars.AWS_OIDC_ROLE }}
          role-session-name: GitHub_and_AWS_OIDC_session
          aws-region: ap-south-1

      - name: Get AWS Account ID
        id: aws-account
        run: |
          ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text)
          echo "AWS_ACCOUNT_ID=$ACCOUNT_ID" >> $GITHUB_ENV

      - uses: azure/setup-helm@v4.2.0
        with:
          version: "latest"

      - name: Install Karpenter Controller
        if: ${{ inputs.action == 'create/update' }}
        run: |
          aws eks update-kubeconfig --name ${{ inputs.eks_cluster_name }} --region ap-south-1
          helm repo add eks https://aws.github.io/eks-charts
          helm repo update eks
          helm upgrade --install karpenter oci://public.ecr.aws/karpenter/karpenter --version ${{ inputs.karpenter_version }} --namespace "karpenter" --create-namespace \
            --set "settings.clusterName=${{ inputs.eks_cluster_name }}" \
            --set controller.resources.requests.cpu=1 \
            --set controller.resources.requests.memory=1Gi \
            --set controller.resources.limits.cpu=1 \
            --set controller.resources.limits.memory=1Gi \
            --set serviceAccount.create=true \
            --set serviceAccount.name=karpenter \
            --wait

      - name: Load values.yaml
        run: |
          aws ssm get-parameter --name '${{ vars.HELM_KARPENTER }}' | jq -r '.Parameter.Value' > ../helm-charts/karpenter-nodegroup/karpenter-values.yaml

      - name: Setup Nodepool
        if: ${{ inputs.action == 'create/update' }}
        run: |
          cd ../
          helm upgrade --install karpenter-nodepool helm-charts/karpenter-nodegroup -f helm-charts/karpenter-nodegroup/karpenter-values.yaml
