apiVersion: karpenter.k8s.aws/v1
kind: EC2NodeClass
metadata:
  name: karpenter-nodeclass
spec:
  amifamily: Bottlerocket
  amiSelectorTerms:
    - id: ami-002f6e91abff6eb96
  role: {{ .Values.role }}
  securityGroupSelectorTerms:
    - tags:
        aws:eks:cluster-name: apollo-poc
  subnetSelectorTerms:
    {{- range .Values.subnets }}
      - id: {{ . }}
    {{- end }}

---
apiVersion: karpenter.sh/v1
kind: NodePool
metadata:
  name: karpenter-nodepool
spec:
  disruption:
    consolidationPolicy: WhenEmptyOrUnderutilized
    consolidateAfter: 10m
  limits:
    cpu: 10
  template:
    spec:
      expireAfter: 1h
      nodeClassRef:
        group: karpenter.k8s.aws
        kind: EC2NodeClass
        name: default
      requirements:
        - key: "karpenter.k8s.aws/instance-category"
          operator: In
          values: ["c", "m", "r", "t"]
        - key: "karpenter.k8s.aws/instance-cpu"
          operator: In
          values: ["4", "8", "16", "32"]
        - key: "kubernetes.io/arch"
          operator: In
          values: ["amd64"]
        - key: "karpenter.sh/capacity-type"
          operator: In
          values: ["on-demand"]
        - key: "kubernetes.io/os"
          operator: In
          values: ["linux"]
